stages:
  load_data:
    cmd: python scr/load_data.py --config=params.yaml
    deps:
      - scr/get_data.py
      - scr/load_data.py
      - data_given/winequality.csv
    outs:
      - data/raw/winequality.csv