stages:
  load_data:
    cmd: python scr/load_data.py --config=params.yaml
    deps:
      - scr/get_data.py
      - scr/load_data.py
      - data_given/winequality.csv
    outs:
      - data/raw/winequality.csv
  split_data:
    cmd: python scr/split_data.py --config=params.yaml
    deps:
      - scr/split_data.py
      - data/raw/winequality.csv
    outs:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv